### ISSUE TITLE
Failure on Travis CI Exec code 134

### ISSUE THREAD

**Issue by markov00** [storybooks/storybook-deployer#57]
Hi, I'm trying to get the deployer working on travis. Locally works fine.

Everything seems to be configured correctly, but during the build I'm getting the following error:

```
Error: Exec code(134) on executing: build-storybook  -o out6368
undefined
    at Object.exec (/home/travis/build/elastic/elastic-charts/node_modules/@storybook/storybook-deployer/src/utils.js:14:9)
    at buildStorybook (/home/travis/build/elastic/elastic-charts/node_modules/@storybook/storybook-deployer/src/build.js:18:18)
    at module.exports (/home/travis/build/elastic/elastic-charts/node_modules/@storybook/storybook-deployer/src/build.js:81:5)
    at Object.<anonymous> (/home/travis/build/elastic/elastic-charts/node_modules/@storybook/storybook-deployer/bin/storybook_to_ghpages:24:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Script failed with status 1
```
This is the failing build: https://travis-ci.org/elastic/elastic-charts/builds/489850823

GH_TOKEN is correctly configured (I'm using this for semantic-release) and the deployer is configured to use `--ci` args:

```
deploy:
  provider: script
  script: yarn storybook:deploy --ci
  skip_cleanup: true
  on:
    branch: master
```

**Comment by markov00** [comment]
I think that could be caused  by insufficient amount of memory on node. 
I didn't tested with storybook-deployer, but a simple storybook static build on travis receive an out of memory.
I've miss configured storybook webpack on add `inline-source-map`also on PRODUCTION env. I've changed it to source map files, and increased a bit the node memory and that worked fine.

**Comment by bietkul** [comment]
I am getting it again in my local, any solution for it?

**Comment by shadiabuhilal** [comment]
I have faced the same issue, and I found the solution.
You need to create babel config file inside `.storybook` directory, to allow babel to build your project correctly.

**Note:**  you can require the root babel config using `babel.config.js` file.

For more info please check https://storybook.js.org/docs/configurations/custom-babel-config/#docs-content
