### ISSUE TITLE
--source-branch=story-test fails

### ISSUE THREAD

**Issue by sOstrovsky** [storybooks/storybook-deployer#61]
Have some problems with dynamic change of source branch.
Can anybody help me with that? Thanks in advance!

`Error: Exec code(1) on executing: git push --force --quiet https://github.com/***/staticStoryBook.git story-test:gh-pages
undefined
    at Object.exec (/Users/***/WebstormProjects/Static StoryBook/node_modules/@storybook/storybook-deployer/src/utils.js:14:9)
    at Object.<anonymous> (/Users/***/WebstormProjects/Static StoryBook/node_modules/@storybook/storybook-deployer/bin/storybook_to_ghpages:69:14)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! static_storybook@0.1.0 deploy-storybook: `storybook-to-ghpages "--source-branch=story-test"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the static_storybook@0.1.0 deploy-storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2019-05-07T15_50_04_243Z-debug.log
`

**Comment by shadiabuhilal** [comment]
Try to create babel config file inside .storybook directory, to allow babel to build your project correctly.

Note: you can require the root babel config using babel.config.js file.

For more info please check https://storybook.js.org/docs/configurations/custom-babel-config/#docs-content
